baseurl = "/"
title = "Private Email Discussion Groups | Group Mailing List Service"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

	[[menu.main]]
		name = "HOME"
		weight = 1
		identifier = "index.html"
		url = "/"
	[[menu.main]]
		name = "Services"
		parent = ""
		identifier = "Services"
		weight =2
		url = "#"
	[[menu.main]]
		name = "Compare"
		weight = 3
		identifier = "Compare"
		url = "Compare.html"	
	[[menu.main]]
		name = "Pricing"
		parent = ""
		weight = 4
		url = "Pricing"
	[[menu.main]]
		name = "About"
		parent = ""
		identifier = "About"
		weight = 5
		url = "/About/"
	[[menu.main]]
		name = "Contact Us"
		parent = ""
		weight = 6
		url = "/contact/"
	[[menu.main]]
		name = "Login"
		parent = ""
		weight = 7
		url = "https://database.mail-list.com/app/login"


# Top bar social links menu

[[menu.social]]
    weight = 1
    name = "Facebook"
    url = "https://www.facebook.com/ListServeCowboy "
    pre = "fa-facebook"

[[menu.social]]
    weight = 2
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/markdavidmccreary"
    pre = "fa-linkedin"

[[menu.social]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/listservecowboy"
    pre = "fa-twitter"

[[menu.social]]
    weight = 4
    name = "Youtube"
    url = "https://www.youtube.com/user/maillistcom"
    pre = "fa-youtube"
	
[[menu.Footerlegal]]
		name = "Mail List Privacy"
		weight = 1
		url = "/privacy/"
	[[menu.Footerlegal]]
		name = "Security"
		weight = 2
		url = "/Security/"
	[[menu.Footerlegal]]
		name = "Terms of Service"
		weight = 3
		url = "/terms-of-service/"
	
	[[menu.Footerabout]]
		name = "User Guide"
		weight = 1
		url = "http://help.mail-list.com/m/59124"
	[[menu.Footerabout]]
		name = "FAQs"
		weight = 2
		url = "/frequently-asked-questions/"
	[[menu.Footerabout]]
		name = "Videos"
		weight = 3
		url = "#"
	[[menu.Footerabout]]
		name = "Blog"
		parent = ""
		weight = 3
		url = "#"
	[[menu.Footerabout]]
		name = "News"
		parent = ""
		weight = 4
		url = "https://www.mail-list.com/news/"
	

[params]
    viewMorePostLink = "/blog/"
    author = ""
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by  using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = " "

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "webuimaker@gmail.com"

    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright © 1995-2017 Mail-List.com All Rights Reserved "

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"
    webadress ="http://www.mail-list.com"
	tel= "713-520-4500"
	contactLogo = "http://www.mail-list.com/wp-content/uploads/2016/08/earhead-1.png?x80233"
    logo = "img/logo.png"
    address = """1302 Waugh Drive, #438 <br> Houston, Texas 77019     
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"


# Enable and disable widgets for the right sidebar
[params.widgets]
    #categories = true
    tags = true
    #search = false

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Email Discussion Group Clients Include:"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
	

